//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSceneryManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\X-Plane9")]
        public string XPlaneFolder {
            get {
                return ((string)(this["XPlaneFolder"]));
            }
            set {
                this["XPlaneFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Scenery (Disabled)")]
        public string DisabledSceneryFolder {
            get {
                return ((string)(this["DisabledSceneryFolder"]));
            }
            set {
                this["DisabledSceneryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maps.google.com/maps/place?q={0},{1}")]
        public string GoogleMapLATLONG {
            get {
                return ((string)(this["GoogleMapLATLONG"]));
            }
            set {
                this["GoogleMapLATLONG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bing.com/maps/default.aspx?q={0},{1}")]
        public string BingMapLATLONG {
            get {
                return ((string)(this["BingMapLATLONG"]));
            }
            set {
                this["BingMapLATLONG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.jetplan.com/jeppesen/jsp/weather/aocTextWeather.jsp?icao={0}&rt=METAR")]
        public string Metar {
            get {
                return ((string)(this["Metar"]));
            }
            set {
                this["Metar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.flightstats.com/go/Airport/airportDetails.do?airport={0}")]
        public string FlightStats {
            get {
                return ((string)(this["FlightStats"]));
            }
            set {
                this["FlightStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.worldaerodata.com/wad.cgi?airport={0}")]
        public string WorldAeroData {
            get {
                return ((string)(this["WorldAeroData"]));
            }
            set {
                this["WorldAeroData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSceneryDownloadFolder {
            get {
                return ((string)(this["LastSceneryDownloadFolder"]));
            }
            set {
                this["LastSceneryDownloadFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://forums.x-plane.org/index.php?app=core&module=global&section=rss&type=downl" +
            "oads")]
        public string RSS_1 {
            get {
                return ((string)(this["RSS_1"]));
            }
            set {
                this["RSS_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Muni,Municipal,Field,Airport,International,Intl,Heliport,sealane,base")]
        public string AptMatchWords {
            get {
                return ((string)(this["AptMatchWords"]));
            }
            set {
                this["AptMatchWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://maps.google.com/maps?q={0} ({1})")]
        public string GoogleMapPLACE {
            get {
                return ((string)(this["GoogleMapPLACE"]));
            }
            set {
                this["GoogleMapPLACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://skyvector.com/?ll={0},{1}&zoom=4")]
        public string SkyVector {
            get {
                return ((string)(this["SkyVector"]));
            }
            set {
                this["SkyVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bing.com/maps/default.aspx?q={0} ({1})")]
        public string BingMapPLACE {
            get {
                return ((string)(this["BingMapPLACE"]));
            }
            set {
                this["BingMapPLACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://forums.x-pilot.com/index.php/rss/downloads/")]
        public string RSS_2 {
            get {
                return ((string)(this["RSS_2"]));
            }
            set {
                this["RSS_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" http://www.openstreetmap.org/search?query={0}")]
        public string OSMPLACE {
            get {
                return ((string)(this["OSMPLACE"]));
            }
            set {
                this["OSMPLACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" http://www.openstreetmap.org/search?query={0},{1}")]
        public string OSMLATLONG {
            get {
                return ((string)(this["OSMLATLONG"]));
            }
            set {
                this["OSMLATLONG"] = value;
            }
        }
    }
}
